#!/usr/bin/env python3
"""
build_knowledge_db.py - Build a Knowledge RAG SQLite database
for TizenClaw from Tizen documentation and glibc man pages.

Generates embeddings via Gemini API (text-embedding-004) and
stores them in a SQLite DB compatible with EmbeddingStore.

Usage:
  python3 tools/build_knowledge_db.py \
    --tizen-docs ~/samba/github/tizen-docs \
    --output data/tizen_knowledge.db \
    --api-key $GEMINI_API_KEY
"""

import argparse
import gzip
import json
import os
import re
import sqlite3
import struct
import subprocess
import sys
import time
import urllib.error
import urllib.request
from html.parser import HTMLParser
from pathlib import Path


# ─── Constants ───────────────────────────────────────────────

CHUNK_SIZE = 1000
CHUNK_OVERLAP = 100
EMBEDDING_DIM = 768
EMBEDDING_MODEL = "gemini-embedding-001"
BATCH_SIZE = 50
MAX_RETRIES = 15
INITIAL_BACKOFF = 15.0

# Tizen API HTML file pattern
CAPI_PATTERN = re.compile(r'^group__CAPI.*\.html$')

# glibc man page pattern (include .3.gz, exclude .3pm.gz etc.)
MAN3_INCLUDE = re.compile(r'.*\.\d+\.gz$')
MAN3_EXCLUDE = re.compile(
    r'.*\.(3pm|3perl|3tcl|3tiff|3ssl|3x)\.gz$',
    re.IGNORECASE
)


# ─── HTML Parser for Doxygen pages ───────────────────────────

class DoxygenHTMLParser(HTMLParser):
    """Extract structured text from Doxygen-generated HTML."""

    def __init__(self):
        super().__init__()
        self._text_parts = []
        self._skip = False
        self._skip_tags = {
            'script', 'style', 'nav', 'head'
        }
        self._depth = 0

    def handle_starttag(self, tag, attrs):
        if tag in self._skip_tags:
            self._skip = True
            self._depth += 1
        cls = dict(attrs).get('class', '')
        if 'navpath' in cls or 'tablist' in cls:
            self._skip = True
            self._depth += 1
        if tag in ('br', 'p', 'div', 'h1', 'h2',
                    'h3', 'h4', 'tr', 'li'):
            self._text_parts.append('\n')

    def handle_endtag(self, tag):
        if tag in self._skip_tags or self._depth > 0:
            self._depth = max(0, self._depth - 1)
            if self._depth == 0:
                self._skip = False

    def handle_data(self, data):
        if not self._skip:
            self._text_parts.append(data)

    def get_text(self):
        raw = ''.join(self._text_parts)
        # Clean up whitespace
        lines = []
        for line in raw.split('\n'):
            line = line.strip()
            if line:
                lines.append(line)
        return '\n'.join(lines)


def parse_doxygen_html(filepath):
    """Parse a Doxygen HTML file and return clean text."""
    try:
        with open(filepath, 'r', encoding='utf-8',
                  errors='replace') as f:
            content = f.read()
    except Exception as e:
        print(f"  WARN: Cannot read {filepath}: {e}")
        return ""

    parser = DoxygenHTMLParser()
    parser.feed(content)
    text = parser.get_text()

    # Remove common Doxygen boilerplate
    text = re.sub(
        r'Generated by Doxygen.*$', '', text,
        flags=re.MULTILINE
    )
    text = re.sub(
        r'Tizen Native API\s+\d+\.\d+', '', text
    )

    return text.strip()


# ─── Markdown Parser ─────────────────────────────────────────

def parse_markdown(filepath):
    """Parse a Markdown file, stripping YAML frontmatter."""
    try:
        with open(filepath, 'r', encoding='utf-8',
                  errors='replace') as f:
            content = f.read()
    except Exception as e:
        print(f"  WARN: Cannot read {filepath}: {e}")
        return ""

    # Strip YAML frontmatter
    if content.startswith('---'):
        end = content.find('---', 3)
        if end != -1:
            content = content[end + 3:]

    return content.strip()


# ─── Man Page Parser ─────────────────────────────────────────

def parse_man_page(filepath):
    """Parse a gzipped man page to plain text using man."""
    try:
        result = subprocess.run(
            ['man', '-l', str(filepath)],
            capture_output=True, text=True,
            timeout=10,
            env={**os.environ, 'MANWIDTH': '80',
                 'PAGER': 'cat',
                 'MAN_KEEP_FORMATTING': ''}
        )
        if result.returncode == 0 and result.stdout:
            return result.stdout.strip()
    except (subprocess.TimeoutExpired, Exception):
        pass

    # Fallback: decompress and strip nroff
    try:
        with gzip.open(filepath, 'rt',
                       encoding='utf-8',
                       errors='replace') as f:
            raw = f.read()
        # Basic nroff cleanup
        raw = re.sub(r'\.\w+.*$', '', raw,
                     flags=re.MULTILINE)
        raw = re.sub(r'\\f[BIRP]', '', raw)
        raw = re.sub(r'\\[-(]..', '', raw)
        return raw.strip()
    except Exception:
        return ""


# ─── Text Chunking ───────────────────────────────────────────

def chunk_text(text, chunk_size=CHUNK_SIZE,
               overlap=CHUNK_OVERLAP):
    """
    Split text into chunks, matching
    EmbeddingStore::ChunkText behavior.
    """
    chunks = []
    if not text or chunk_size == 0:
        return chunks

    pos = 0
    while pos < len(text):
        end = min(pos + chunk_size, len(text))

        # Try to break at sentence boundary
        if end < len(text):
            last_period = text.rfind('.', pos, end)
            if (last_period != -1 and
                    last_period > pos + chunk_size // 2):
                end = last_period + 1

        chunks.append(text[pos:end])

        if end >= len(text):
            break

        # Next chunk starts with overlap
        pos = max(end - overlap, end)
        if pos == end - overlap and pos <= 0:
            pos = end

    return chunks


# ─── Gemini Embedding API ────────────────────────────────────

def generate_embeddings_batch(texts, api_key,
                              model=EMBEDDING_MODEL):
    """
    Call Gemini embedding API with a batch of texts.
    Returns list of embedding vectors.
    """
    url = (
        f"https://generativelanguage.googleapis.com/"
        f"v1beta/models/{model}:batchEmbedContents"
        f"?key={api_key}"
    )

    requests_list = []
    for text in texts:
        # Truncate very long texts
        if len(text) > 8000:
            text = text[:8000]
        requests_list.append({
            "model": f"models/{model}",
            "content": {"parts": [{"text": text}]},
            "taskType": "RETRIEVAL_DOCUMENT"
        })

    payload = json.dumps(
        {"requests": requests_list}
    ).encode('utf-8')

    req = urllib.request.Request(
        url,
        data=payload,
        headers={'Content-Type': 'application/json'},
        method='POST'
    )

    for attempt in range(MAX_RETRIES):
        try:
            with urllib.request.urlopen(
                    req, timeout=60) as resp:
                data = json.loads(resp.read())

            embeddings = []
            for emb_obj in data.get(
                    'embeddings', []):
                embeddings.append(
                    emb_obj['values']
                )
            return embeddings

        except urllib.error.HTTPError as e:
            if e.code in (429, 500, 503):
                wait = INITIAL_BACKOFF * (2 ** attempt)
                print(f"  Rate limited ({e.code}), "
                      f"retrying in {wait:.0f}s...")
                time.sleep(wait)
                continue
            print(f"  HTTP error {e.code}: "
                  f"{e.read().decode()[:200]}")
            raise
        except Exception as e:
            if attempt < MAX_RETRIES - 1:
                wait = INITIAL_BACKOFF * (2 ** attempt)
                print(f"  Error: {e}, retrying in "
                      f"{wait:.0f}s...")
                time.sleep(wait)
                continue
            raise

    raise RuntimeError(
        f"Failed after {MAX_RETRIES} retries"
    )


# ─── SQLite Database ─────────────────────────────────────────

def init_database(db_path):
    """Create SQLite DB with EmbeddingStore schema."""
    conn = sqlite3.connect(db_path)
    conn.execute(
        "CREATE TABLE IF NOT EXISTS documents ("
        "  id INTEGER PRIMARY KEY AUTOINCREMENT,"
        "  source TEXT NOT NULL,"
        "  chunk_text TEXT NOT NULL,"
        "  embedding BLOB NOT NULL,"
        "  created_at TEXT DEFAULT "
        "    (datetime('now'))"
        ");"
    )
    conn.commit()
    return conn


def store_chunk(conn, source, chunk_text, embedding):
    """Store a single chunk with its embedding as float16."""
    # Convert float32 list to float16 binary blob using struct 'e' (half precision)
    blob = struct.pack(f'<{len(embedding)}e', *embedding)
    
    conn.execute(
        "INSERT INTO documents "
        "(source, chunk_text, embedding) "
        "VALUES (?, ?, ?);",
        (source, chunk_text, blob)
    )


def get_processed_sources(conn):
    """Get set of already-processed source names."""
    cursor = conn.execute(
        "SELECT DISTINCT source FROM documents;"
    )
    return {row[0] for row in cursor}


# ─── Content Discovery ───────────────────────────────────────

def discover_tizen_guides(tizen_docs_path):
    """Find all native guide MD files."""
    guides_dir = (
        Path(tizen_docs_path) /
        "docs/application/native/guides"
    )
    if not guides_dir.exists():
        print(f"WARN: Guides dir not found: "
              f"{guides_dir}")
        return []

    files = sorted(guides_dir.rglob("*.md"))
    return files


def discover_api_html(tizen_docs_path):
    """Find all CAPI Doxygen HTML files."""
    api_dir = (
        Path(tizen_docs_path) /
        "docs/application/native/api/common/10.0"
    )
    if not api_dir.exists():
        print(f"WARN: API dir not found: {api_dir}")
        return []

    files = []
    for f in sorted(api_dir.iterdir()):
        if f.is_file() and CAPI_PATTERN.match(f.name):
            files.append(f)
    return files


def discover_man_pages(man_dir="/usr/share/man/man3"):
    """Find C-relevant man3 pages."""
    man_path = Path(man_dir)
    if not man_path.exists():
        print(f"WARN: Man dir not found: {man_dir}")
        return []

    files = []
    for f in sorted(man_path.iterdir()):
        if not f.is_file():
            continue
        if MAN3_EXCLUDE.match(f.name):
            continue
        if MAN3_INCLUDE.match(f.name):
            files.append(f)
    return files


# ─── Main Pipeline ────────────────────────────────────────────

def process_files(files, parser_fn, category,
                  conn, api_key, resume_sources,
                  dry_run=False):
    """
    Process a list of files: parse → chunk → embed → store.
    """
    total = len(files)
    processed = 0
    skipped = 0
    chunks_total = 0

    pending_chunks = []   # (source, text)
    pending_texts = []    # Just texts for batching

    def flush_batch():
        nonlocal chunks_total
        if not pending_texts or dry_run:
            return

        embeddings = generate_embeddings_batch(
            pending_texts, api_key
        )

        for (src, txt), emb in zip(
                pending_chunks, embeddings):
            store_chunk(conn, src, txt, emb)
            chunks_total += 1

        conn.commit()
        pending_chunks.clear()
        pending_texts.clear()

    for i, filepath in enumerate(files):
        source = f"{category}:{filepath.name}"

        if source in resume_sources:
            skipped += 1
            continue

        text = parser_fn(filepath)
        if not text or len(text) < 50:
            continue

        chunks = chunk_text(text)
        if not chunks:
            continue

        processed += 1

        if dry_run:
            chunks_total += len(chunks)
            if (i + 1) % 50 == 0 or i == total - 1:
                print(f"  [{i+1}/{total}] "
                      f"{filepath.name}: "
                      f"{len(chunks)} chunks")
            continue

        for chunk in chunks:
            pending_chunks.append((source, chunk))
            pending_texts.append(chunk)

            if len(pending_texts) >= BATCH_SIZE:
                flush_batch()
                # Delay to stay within rate limits (15 RPM for free tier)
                time.sleep(4.5)

        if (i + 1) % 20 == 0 or i == total - 1:
            print(f"  [{i+1}/{total}] "
                  f"Processed: {processed}, "
                  f"Chunks: {chunks_total}")

    # Flush remaining
    flush_batch()

    print(f"  {category}: {processed} files, "
          f"{chunks_total} chunks "
          f"({skipped} skipped/resumed)")
    return chunks_total


def main():
    parser = argparse.ArgumentParser(
        description="Build TizenClaw Knowledge "
                    "RAG Database"
    )
    parser.add_argument(
        '--tizen-docs', required=True,
        help='Path to tizen-docs repository'
    )
    parser.add_argument(
        '--output', required=True,
        help='Output SQLite database path'
    )
    parser.add_argument(
        '--api-key',
        default=os.environ.get('GEMINI_API_KEY', ''),
        help='Gemini API key '
             '(or set GEMINI_API_KEY env var)'
    )
    parser.add_argument(
        '--man-dir',
        default='/usr/share/man/man3',
        help='Man pages directory'
    )
    parser.add_argument(
        '--resume', action='store_true',
        help='Resume from where we left off '
             '(skip already-processed sources)'
    )
    parser.add_argument(
        '--dry-run', action='store_true',
        help='Parse and chunk only, '
             'no API calls or DB writes'
    )
    parser.add_argument(
        '--skip-guides', action='store_true',
        help='Skip Tizen native guides'
    )
    parser.add_argument(
        '--skip-api', action='store_true',
        help='Skip Tizen API reference HTML'
    )
    parser.add_argument(
        '--skip-man', action='store_true',
        help='Skip glibc man pages'
    )

    args = parser.parse_args()

    if not args.dry_run and not args.api_key:
        print("ERROR: Gemini API key required. "
              "Set GEMINI_API_KEY or use --api-key")
        sys.exit(1)

    tizen_docs = Path(args.tizen_docs)
    if not tizen_docs.exists():
        print(f"ERROR: tizen-docs not found: "
              f"{tizen_docs}")
        sys.exit(1)

    # Ensure output directory exists
    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    print("=" * 50)
    print("TizenClaw Knowledge RAG Builder")
    print("=" * 50)

    # Initialize database
    if args.dry_run:
        conn = None
        resume_sources = set()
        print("Mode: DRY RUN (no API calls)")
    else:
        conn = init_database(str(out_path))
        if args.resume:
            resume_sources = get_processed_sources(
                conn
            )
            print(f"Resuming: {len(resume_sources)} "
                  f"sources already processed")
        else:
            resume_sources = set()

    total_chunks = 0

    # 1. Tizen Native Guides (MD)
    if not args.skip_guides:
        print("\n── Tizen Native Guides ──")
        guides = discover_tizen_guides(
            str(tizen_docs)
        )
        print(f"Found {len(guides)} guide files")
        if guides:
            total_chunks += process_files(
                guides, parse_markdown, "guide",
                conn, args.api_key,
                resume_sources, args.dry_run
            )

    # 2. Tizen Native C API Reference (HTML)
    if not args.skip_api:
        print("\n── Tizen Native C API Reference ──")
        api_files = discover_api_html(
            str(tizen_docs)
        )
        print(f"Found {len(api_files)} API files")
        if api_files:
            total_chunks += process_files(
                api_files, parse_doxygen_html,
                "api", conn, args.api_key,
                resume_sources, args.dry_run
            )

    # 3. glibc Man Pages
    if not args.skip_man:
        print("\n── glibc Man Pages ──")
        man_files = discover_man_pages(args.man_dir)
        print(f"Found {len(man_files)} man pages")
        if man_files:
            total_chunks += process_files(
                man_files, parse_man_page, "man",
                conn, args.api_key,
                resume_sources, args.dry_run
            )

    # Summary
    print("\n" + "=" * 50)
    print(f"Total chunks: {total_chunks}")
    if conn:
        final_count = get_processed_sources(conn)
        total_in_db = conn.execute(
            "SELECT COUNT(*) FROM documents"
        ).fetchone()[0]
        print(f"Total sources in DB: "
              f"{len(final_count)}")
        print(f"Total chunks in DB: {total_in_db}")
        db_size = out_path.stat().st_size
        print(f"Database size: "
              f"{db_size / 1024 / 1024:.1f} MB")
        conn.close()
    print(f"Output: {out_path}")
    print("=" * 50)


if __name__ == '__main__':
    main()
