import os
import json
import logging
from enum import Enum
from typing import List, Dict, Any, Optional
from datetime import datetime

logger = logging.getLogger(__name__)

class MemoryType(Enum):
    SHORT_TERM = "short_term"
    LONG_TERM = "long_term"
    EPISODIC = "episodic"

class MemoryEntry:
    def __init__(self, mem_type: MemoryType, title: str, content: str, 
                 tags: List[str] = None, importance: str = "medium", 
                 created: str = None, updated: str = None):
        self.type = mem_type
        self.title = title
        self.content = content
        self.tags = tags or []
        self.importance = importance
        self.created = created or datetime.utcnow().isoformat()
        self.updated = updated or self.created

class MemoryConfig:
    def __init__(self):
        self.short_term_max_age_hours = 24
        self.short_term_max_entries = 50
        self.long_term_max_file_bytes = 2048
        self.episodic_max_age_days = 30
        self.episodic_max_file_bytes = 2048
        self.summary_max_bytes = 8192
        self.summary_recent_activity = 5
        self.summary_recent_episodic = 10

class MemoryStore:
    """
    Python implementation of TizenClaw MemoryStore.
    Manages semantic LLM memory logs and markdown summaries.
    """
    def __init__(self):
        self.base_dir = "/opt/usr/share/tizenclaw/memory"
        self.config = MemoryConfig()
        self.summary_dirty = False

    def set_directory(self, directory: str):
        self.base_dir = directory
        os.makedirs(self.base_dir, exist_ok=True)

    def load_config(self, path: str) -> bool:
        if not os.path.exists(path):
            return False
        try:
            with open(path, "r", encoding="utf-8") as f:
                data = json.load(f)
            # Apply configuration overrides
            for k, v in data.items():
                if hasattr(self.config, k):
                    setattr(self.config, k, v)
            return True
        except Exception as e:
            logger.error(f"Failed to load memory config: {e}")
            return False

    def write_memory(self, entry: MemoryEntry, filename: str) -> bool:
        dir_path = self._get_type_dir(entry.type)
        os.makedirs(dir_path, exist_ok=True)
        path = os.path.join(dir_path, filename)
        
        try:
            content = self._entry_to_markdown(entry)
            tmp_path = path + ".tmp"
            with open(tmp_path, "w", encoding="utf-8") as f:
                f.write(content)
            os.replace(tmp_path, path)
            self.summary_dirty = True
            return True
        except Exception as e:
            logger.error(f"Failed to write memory: {e}")
            return False

    def regenerate_summary(self):
        # Placeholder for full context summary regeneration
        self.summary_dirty = False
        summary_path = os.path.join(self.base_dir, "memory.md")
        try:
            with open(summary_path, "w", encoding="utf-8") as f:
                f.write("# Memory Summary\nAutogenerated by Python MemoryStore\n")
        except Exception:
            pass

    def load_summary(self) -> str:
        if self.summary_dirty:
            self.regenerate_summary()
        summary_path = os.path.join(self.base_dir, "memory.md")
        if os.path.exists(summary_path):
            with open(summary_path, "r", encoding="utf-8") as f:
                return f.read()
        return ""

    def _get_type_dir(self, mem_type: MemoryType) -> str:
        return os.path.join(self.base_dir, mem_type.value)

    def _entry_to_markdown(self, entry: MemoryEntry) -> str:
        yaml_frontmatter = (
            f"---\n"
            f"type: {entry.type.value}\n"
            f"title: {entry.title}\n"
            f"importance: {entry.importance}\n"
            f"created: {entry.created}\n"
            f"updated: {entry.updated}\n"
            f"---\n\n"
        )
        return yaml_frontmatter + entry.content
